#!/bin/bash

function alias_apt {
    alias upd='sudo apt update'
    alias upg='sudo apt upgrade'
    alias upgy='sudo apt upgrade -y'
    alias ins='sudo apt install'
    alias insy='sudo apt install -y'
    alias insf='sudo apt install -f'
    alias rmv='sudo apt remove'
    alias rmvy='sudo apt remove -y'
    alias prg='sudo apt purge'
    alias prgy='sudo apt purge -y'
    alias atr='sudo apt autoremove'
    alias atry='sudo apt autoremove -y'
    alias dpk='sudo dpkg -i'
}

function alias_git {
    alias glg='git log'
    alias gbr='git branch'
    alias gbrd='git branch -d'
    alias gbrD='git branch -D'
    alias gbrc='git branch --show-current'
    alias gbrm='git branch -m'
    alias gad='git add'
    alias gada='git add -A'
    alias gadu='git add -u'
    alias gst='git status'
    alias gcm='git commit -m'
    alias gcma='git commit --amend'
    alias gss='git stash'
    alias gssc='git stash clear'
    alias gssp='git stash pop'
    alias gck='git checkout'
    alias gckb='git checkout -b'
    alias gmr='git merge'
    alias grs='git reset'
    alias grsh='git reset --hard'
    alias grss='git reset --soft'
    alias gcp='git cherry-pick'
    alias gdf='git diff'
    alias gps='git push'
    alias gpsf='git push --force'
    alias gpso='git push origin'
    alias gpsod='git push origin --delete'
    alias gpss='git push --set-upstream'
    alias gpsso='git push --set-upstream origin'
    alias gpssoc='git push --set-upstream origin $(git branch --show-current)'
    alias gpl='git pull --rebase'
    alias gft='git fetch'
    alias gtg='git tag'
    alias gtgd='git tag --delete'
    alias grt='git remote'
    alias grta='git remote add'
    alias grtg='git remote get-url'
    alias grts='git remote set-url'
    alias grtao='git remote add origin'
    alias grtgo='git remote get-url origin'
    alias grtso='git remote set-url origin'
    alias grm='git rm'
    alias grmc='git rm --cached'
    alias gmv='git mv'
    alias gsh='git show'
    alias gcl='git clean'
    alias gcln='git cln -n'
    alias gclf='git cln -f'
    alias gfb='git filter-branch'
    alias gfbf='git filter-branch -f'
    alias gcl='git clone'
    alias gclr='git clone --recurse-submodules'
    alias gmd='git submodule'
    alias gmdi='git submodule init'
    alias gmdu='git submodule update'
    alias gtr='git subtree'
    alias grv='git revert'
    alias gcf='git config'
    alias gcfg='git config --global'
    alias gcfgn='git config --global user.name'
    alias gcfge='git config --global user.email'
    alias gcfgs='git config --global user.signingkey'
    alias gcfl='git config --local'
    alias gcfln='git config --local user.name'
    alias gcfle='git config --local user.email'
    alias gcfls='git config --local user.signingkey'
    alias grb='git rebase'
}

function alias_py {
    alias spy='nohup spyder3 &'
    alias py='python3'
    alias py3='python3'
    alias pyve='python3 -m venv $HOME/py_venv_default'
    alias pin='pip3 install'
    alias pinu='pip3 install --upgrade'
    alias pun='pip3 uninstall'
    alias pfr='pip3 freeze'
    alias psh='pip3 show'
    alias psr='pip3 search'
    alias pls='pip3 list'
    alias prq='pipreqs --no-pin --encoding=utf8'
    alias prqs='pipreqs --no-pin --encoding=utf8 && echo sphinxcontrib_napoleon >> requirements.txt && echo sphinx_rtd_theme >> requirements.txt && echo m2r2 >> requirements.txt'
    alias prqf='pipreqs --no-pin --encoding=utf8 --force'
    alias prqfs='pipreqs --no-pin --encoding=utf8 --force && echo sphinxcontrib_napoleon >> requirements.txt && echo sphinx_rtd_theme >> requirements.txt && echo m2r2 >> requirements.txt'
    alias pht='python3 -m http.server'
    alias python='python3'
    alias pip='pip3'
}

function alias_ls {
    alias lsl='ls -l'
    alias lsa='ls -a'
    alias lsla='ls -la'
}

function alias_rm {
    alias rmrf='rm -rf'
    alias rmr='rm -r'
    alias srm='sudo rm'
    alias srmrf='sudo rm -rf'
    alias srmr='sudo rm -r'
}

function alias_make {
    alias mk='make'
    alias ma='make all'
    alias mc='make clean'
    alias mi='make install'
    alias smi='sudo make install'
}

function alias_bashrc {
    alias bre="subl ~/.bashrc" #Edit
    alias brs="source ~/.bashrc" #Source
}

function alias_misc {
    alias st='subl'
    alias sst='sudo subl'
    alias nn="nano"
}

function alias_chmod {
    alias cx='chmod +x'
    alias scx='sudo chmod +x'
}

function alias_alias {
    alias alap='alias | grep -e "sudo apt" -e "sudo dpkg"'
    alias algt='alias | grep -e git'
    alias alpy='alias | grep -e python -e pip'
    alias alcn='alias | grep -e conda'
    alias almk='alias | grep -e make'
    alias albr='alias | grep -e bashrc'
}

alias_apt
alias_git
alias_py
alias_ls
alias_rm
alias_make
alias_bashrc
alias_misc
alias_chmod
alias_alias
