#!/bin/bash

export PATH="$HOME/.local/bin:/usr/local/cuda/bin/:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda/targets/x86_64-linux/lib"

# Make and CD
function mcd {
	mkdir $1 && cd $1
}

# PDF Grep Current
function pgc {
	pdfgrep -lr "$1" ./
}