#!/bin/bash

export GPG_TTY=$(tty)

# Make and CD
function mcd {
    mkdir -p $1 && cd $1
}

function pip3() {
    VENV_PATH="$HOME/py_venv_default"

    if [ -f "$VENV_PATH/pyvenv.cfg" ]; then
        echo "Starting pip in default venv"
        env VIRTUAL_ENV="$VENV_PATH" "$VENV_PATH/bin/pip3" "$@"
    else
        echo "Starting pip in global environment"
        /usr/bin/pip3 "$@"
    fi
}

function python3() {
    VENV_PATH="$HOME/py_venv_default"

    if [ -f "$VENV_PATH/pyvenv.cfg" ]; then
        echo "Starting python in default venv"
        env VIRTUAL_ENV="$VENV_PATH" "$VENV_PATH/bin/python3" "$@"
    else
        echo "Starting python in global environment"
        /usr/bin/python3 "$@"
    fi
}

# Install all apt packages
function ins_apt_pkgs {
    ESSENTIALS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    sudo apt update
    sudo apt upgrade -y
    sudo apt install -y wget curl git make cmake default-jdk build-essential xclip gimp net-tools python3-pip
}

# Install all pip packages
function ins_pip_pkgs {
    pip3 install --upgrade pip
    pip3 install numpy scipy matplotlib spyder pandas
}

# setup - Install Necessary Packages on the System
function stp {
    ESSENTIALS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    sudo apt update
    sudo apt upgrade -y
    sudo apt autoremove -y
    sudo apt install python3 git python3-pip
    ins_apt_pkgs &
    ins_pip_pkgs &
    rm -rf $HOME/Desktop
    rm -rf $HOME/Documents
    rm -rf $HOME/Downloads
    rm -rf $HOME/Music
    rm -rf $HOME/Pictures
    rm -rf $HOME/Videos
    ln -s /mnt/n/Desktop/ $HOME/
    ln -s /mnt/n/Documents/ $HOME/
    ln -s /mnt/n/Downloads/ $HOME/
    ln -s /mnt/n/Music/ $HOME/
    ln -s /mnt/n/Pictures/ $HOME/
    ln -s /mnt/n/Videos/ $HOME/
    mkdir -p $HOME/Pictures/Wallpapers
    cp $ESSENTIALS_DIR/wallpapers/* $HOME/Pictures/Wallpapers/
    gsettings set org.gnome.desktop.background picture-uri file:////$HOME/Pictures/Wallpapers/RoboISM\ Logo.png
}

# Generate ed25519 SSH-Key
# Might not work on Windows
function sk {
    TARGET=$1
    if [ "$1" = "gh" ]; then
        TARGET="github"
    elif [ "$1" = "gl" ]; then
        TARGET="gitlab"
    elif [ "$1" = "bb" ]; then
        TARGET="bitbucket"
    elif [ "$1" = "ol" ]; then
        TARGET="overleaf"
    elif [ "$1" = "rp" ]; then
        TARGET="raspberrypi"
    fi
    OS=$(lsb_release -is)
    VER=$(lsb_release -cs)
    MODEL=$(cat /sys/devices/virtual/dmi/id/product_name)
    KEY_COMMENT="$MODEL - $OS $VER"
    KEY_PRV="$HOME/.ssh/ed25519_$TARGET"
    KEY_PUB="$KEY_PRV.pub"
    ssh-keygen -t ed25519 -f $KEY_PRV -C "$KEY_COMMENT"
    cat $KEY_PUB | xclip -selection clipboard
}

# Kill process on a port
function kp {
    PID=$(sudo lsof -t -i:$1)
    if [ "$PID" = "" ]; then
        echo "No Process Running on Port $1"
    else
        sudo kill -9 $(sudo lsof -t -i:$1)
    fi
}
