#!/bin/bash

function path_hist_to_repo {
	PATH_HIST_TO_REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
	alias gptr="python3 $PATH_HIST_TO_REPO_DIR/git_filter.py"
	alias gptrf="python3 $PATH_HIST_TO_REPO_DIR/git_filter.py -f"
	alias gptrnb="python3 $PATH_HIST_TO_REPO_DIR/git_filter.py -nb"
	alias gptrfnb="python3 $PATH_HIST_TO_REPO_DIR/git_filter.py -f -nb"
}

path_hist_to_repo
